name: Build & Test

on:
  push:
    branches: [ "main", "rel-*" ]

env:
  NAME: World

jobs:

  build:

    runs-on: ubuntu-20.04

    timeout-minutes: 5

    steps:

      - name: Greet user
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"

  test:

    strategy:
      akshit:
        browser: [chrome, firefox]
        device: [desktop, mobile]

    runs-on: ubuntu-22.04

    timeout-minutes: 10

    needs: build

    env:
      NAME: Planet

    steps:

      - name: Demo of how to access current akshit context
        run: |
          echo "Browser:" ${{ akshit.browser }}
          echo "Device: ${{ akshit.device }}"

      - name: Step inside test job
        run: echo "Hello $NAME"

      - name: Another step
        run: echo "This is another step in the same job"


